# Generated by Django 4.0.10 on 2023-04-24 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('eve_fleet_id', models.BigIntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('events', models.IntegerField(default=0)),
                ('refresh_time', models.IntegerField(default=10)),
                ('name', models.CharField(max_length=200)),
                ('after_action_report', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('motd', models.TextField(blank=True, null=True)),
                ('boss', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='eveonline.evecharacter')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FleetType',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('counts_in_statistics', models.BooleanField(default=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ShipCategory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('constellation', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='aacat.constellation')),
                ('region', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='aacat.region')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='ShipType',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('cat', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='aacat.shipcategory')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='FleetEvent',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('character_id', models.BigIntegerField()),
                ('join_time', models.DateTimeField()),
                ('ship_type_id', models.IntegerField()),
                ('station_id', models.BigIntegerField(default=None, null=True)),
                ('role', models.CharField(max_length=25)),
                ('squad_id', models.BigIntegerField()),
                ('wing_id', models.BigIntegerField(default=None, null=True)),
                ('takes_fleet_warp', models.BooleanField(default=False)),
                ('character_name', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveonline.evecharacter')),
                ('fleet', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='aacat.fleet')),
                ('ship', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='aacat.shiptype')),
                ('solar_system', models.ForeignKey(
                    null=True, on_delete=django.db.models.deletion.SET_NULL, to='aacat.system')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='fleet',
            name='fleet_type',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='aacat.fleettype'),
        ),
        migrations.AddField(
            model_name='constellation',
            name='region',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to='aacat.region'),
        ),
        migrations.CreateModel(
            name='CATConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_monitoring_mode', models.BooleanField(default=False)),
                ('monitor_groups', models.ManyToManyField(
                    blank=True, to='auth.group')),
            ],
            options={
                'verbose_name': 'aaCAT Configuration',
                'permissions': (('monitor_us', 'CAT Fleet Auto Monitoring for ALL fleets run by these users'), ('create_fleets', 'Can Create new CAT Fleets'), ('view_fleets', 'Can View all active CAT Fleets'), ('edit_fleets', 'Can Edit all active CAT Fleets'), ('view_self', 'Can view own statistics'), ('view_corp', 'Can view own corp member statistics'), ('view_alli', 'Can view own alliance member statistics'), ('view_global', 'Can view all statistics')),
                'default_permissions': (),
            },
        ),
    ]
