# Generated by Django 4.2.8 on 2023-12-16 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aacat', '0002_fleettype_allowable_fc_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='fleet_type',
            field=models.ForeignKey(blank=True, default=None, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, to='aacat.fleettype'),
        ),
    ]
