# Generated by Django 4.2.8 on 2023-12-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aacat', '0003_alter_fleet_fleet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
