# Generated by Django 4.2.8 on 2023-12-20 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0017_alliance_and_corp_names_are_not_unique'),
        ('aacat', '0004_fleet_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='fc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='fleet_boss', to='eveonline.evecharacter'),
        ),
        migrations.AddField(
            model_name='fleetevent',
            name='distance_from_fc',
            field=models.IntegerField(default=0),
        ),
    ]
