# Generated by Django 4.2.8 on 2023-12-21 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aacat', '0005_fleet_fc_fleetevent_distance_from_fc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetevent',
            name='distance_from_fc',
            field=models.IntegerField(default=-2),
        ),
    ]
